name: travel_translator
description: On-device Japanese to English translator for travelers
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true